# Override rubocop defaults.
# See [defaults](https://github.com/bbatsov/rubocop/blob/master/config/default.yml)

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment: # TODO: Re-enable and address these before Ruby 3.0
  Enabled: false
