# Override rubocop defaults.
#
# * [rubocop defaults](https://github.com/bbatsov/rubocop/blob/master/config/default.yml)
# * [rails defaults](https://github.com/rails/rails/blob/master/.rubocop.yml)

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*_create_versions.rb'
    - 'bin/**/*'
    - 'spec/spec_helper.rb'

# Don't require documenting classes, modules, methods
Documentation:
  Enabled: false

#################### Metrics ###########################

# Allow lines up to 120 characters
Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*.rb'

# Allow long blocks. This includes rake tasks, rake namespaces.
# TODO: can we allow large namespaces, but not the others?
Metrics/BlockLength:
  Enabled: false

#################### Style ###########################

Style/FormatStringToken:
  Enabled: false

Style/StringLiterals:
  Enabled: false # TODO: consider re-enabling. Address 200+ offenses.

Style/FrozenStringLiteralComment:
  Exclude:
    - 'config/**/*.rb'
    - 'db/**/*.rb'
    - 'spec/**/*.rb'
    - 'test/**/*.rb'

# Prefer array literals of symbols over %i(), which requires memorizing "%i"
Style/SymbolArray:
  EnforcedStyle: brackets

Style/ClassAndModuleChildren:
  Exclude:
    - 'spec/models/**/*.rb'
    - 'test/models/**/*.rb'

Style/BlockDelimiters:
  Exclude:
    - 'app/controllers/*_controller.rb'

#################### Layout ###########################

# Indent `protected` and `private` modifiers the same as public methods.
# Indent their members one step more than the modifiers.
Layout/IndentationConsistency:
  EnforcedStyle: rails

# TODO: See what we prefer and enable something
Layout/AccessModifierIndentation:
  Enabled: false

# Allow empty lines around classes
Layout/EmptyLinesAroundClassBody:
  Enabled: false

# Allow empty lines around modules
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# Allow empty lines around blocks
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - config/environments/*.rb
