# Override rubocop defaults.
#
# * [rubocop defaults](https://github.com/bbatsov/rubocop/blob/master/config/default.yml)
# * [rails defaults](https://github.com/rails/rails/blob/main/.rubocop.yml)

require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "node_modules/**/*"
    - "**/templates/**/*"
    - "**/vendor/**/*"
    - "db/schema.rb"
    - "db/migrate/*_create_versions.rb"
    - "bin/**/*"
    - "spec/spec_helper.rb"
    - "**/*.erb" # Workaround for https://github.com/AtomLinter/linter-rubocop/issues/48

#################### Layout ###########################

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

# Allow lines up to 120 characters
Layout/LineLength:
  Max: 120

Layout/SpaceBeforeBlockBraces:
  Exclude:
    - "spec/**/*" # to allow `expect{raise 'foo'}.to raise_error RuntimeError`

Layout/SpaceInsideBlockBraces:
  Exclude:
    - "spec/**/*" # to allow `expect{raise 'foo'}.to raise_error RuntimeError`

#################### Lint ###########################

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

#################### Metrics ###########################

Metrics/MethodLength:
  Exclude:
    - "app/controllers/*_controller.rb"
    - "app/models/ability.rb"
    - "db/migrate/*.rb"

Metrics/AbcSize:
  Exclude:
    - "app/models/ability.rb"
    - "db/migrate/*.rb"

# Allow long blocks. This includes rake tasks, rake namespaces.
# TODO: can we allow large namespaces, but not the others?
Metrics/BlockLength:
  Enabled: false

Performance/MethodObjectAsBlock:
  Exclude:
    - "**/*_search.rb"
    - "**/*_search_form.rb"

#################### Naming ##########################

Naming/InclusiveLanguage:
  Enabled: false

#################### Style ###########################

# Don't require documenting classes, modules, methods
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false # TODO: consider re-enabling. Address 200+ offenses.

Style/FrozenStringLiteralComment:
  Enabled: false
  Exclude:
    - "config/**/*.rb"
    - "db/**/*.rb"
    - "spec/**/*.rb"
    - "test/**/*.rb"

# Prefer array literals of symbols over %i(), which requires memorizing "%i"
Style/SymbolArray:
  EnforcedStyle: brackets

# Either way ok since Ruby 2.5.
# https://www.bigbinary.com/blog/ruby-2.5-has-removed-top-level-constant-lookup
Style/ClassAndModuleChildren:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - "app/controllers/*_controller.rb"
    - "spec/**/*"

#################### Layout ###########################

Layout/HashAlignment:
  Enabled: false

# Indent `protected` and `private` modifiers the same as public methods.
# Indent their members one step more than the modifiers.
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

# TODO: See what we prefer and enable something
Layout/AccessModifierIndentation:
  Enabled: false

# Allow empty lines around classes
Layout/EmptyLinesAroundClassBody:
  Enabled: false

# Allow empty lines around modules
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# Allow empty lines around blocks
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - config/environments/*.rb

#################### Rails ###########################

Rails/EnumHash:
  Enabled: false

Rails/Output:
  Exclude:
    - db/seeds.rb

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - demo

#################### RSpec ###########################

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15

# Use class explicitly, rather than `described_class`.
RSpec/DescribedClass:
  EnforcedStyle: explicit

#### FactoryBot ####
# - https://docs.rubocop.org/rubocop-rspec/cops_rspec_factorybot.html

FactoryBot/SyntaxMethods:
  Enabled: false
