# frozen_string_literal: true

# TODO: REVIEW THIS GENERATED GEMFILE, THEN DELETE THIS COMMENT.
# When applying to an existing project, you must restore any project gems we blew away!

source 'https://rubygems.org'

gem 'rails', '~> 6.1.4'

gem 'dotenv-rails'              # Loads environment variables from .env into ENV, automagically.
gem 'pg', '~> 1.3'              # Use postgresql 9.3+ as the database for Active Record

gem 'authlogic', '~> 6.0'       # Authentication
gem 'cancancan', '~> 3.0'       # Authorization
gem 'scrypt'                    # required by authlogic when using scrypt

gem 'addressable', '~> 2.6'     # more conformant replacement for (obsolete) Ruby URI
gem 'browser'                   # browser detection
gem 'colorize'                  # Colored console output
gem 'fast_jsonapi'              # JSON:API serializer
gem 'friendly_id', '~> 5.4.2'   # Nice URLs
gem 'paper_trail', '~> 12.0'    # Track model revisions
gem 'populate', git: 'git@bitbucket.org:tiu/populate.git'
gem 'tiu-generators', bitbucket: 'tiu/tiu-generators'
gem 'tiutils', git: 'git@bitbucket.org:tiu/tiutils.git'
gem 'will_paginate', '~> 3.3'   # Pagination

# Application Management

gem 'bootsnap', require: false  # Reduces boot times through caching; required in config/boot.rb
gem 'exception_notification', '~> 4.4'
gem 'httparty'                  # used for Google Chat Notifier (Exception Notification)
# gem 'rack-attack'               # block & throttle abusive requests
gem 'rack-timeout', require: 'rack/timeout/base' # Abort requests that are taking too long
gem 'sitemap_generator'         # Generation setup in config/sitemap.rb
gem 'slack-notifier'            # Send exception notifications to Slack
gem 'whenever', require: false  # Schedule cron jobs

# Styling

gem 'autoprefixer-rails'        # CSS vendor prefixer
gem 'bootstrap', '~> 4.2'
gem 'font-awesome-sass', '~> 6.0'
gem 'sass-rails', '~> 6.0'      # Use SCSS for stylesheets. Compiles with libsass for speed.

# Javascript

gem 'mini_racer' # See https://github.com/rails/execjs#readme for more supported runtimes

gem 'jquery-rails'              # Use jquery as the JavaScript library
gem 'uglifier', '>= 1.3.0'      # Use Uglifier as compressor for JavaScript assets
gem 'webpacker', '~> 5.0'       # Transpile app-like JavaScript. TODO: replacement

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]

  gem 'factory_bot_rails'
  gem 'faker', '~> 2.2'
  gem 'rspec-rails', '~> 5.0'

  # https://www.phusionpassenger.com/library/walkthroughs/start/ruby.html
  # gem 'passenger', '~> 5.1', require: 'phusion_passenger/rack_handler'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'

  gem 'listen', '~> 3.2'

  gem 'capistrano',             '~> 3.15', require: false
  gem 'capistrano-maintenance', '~> 1.0', require: false
  gem 'capistrano-passenger'
  gem 'capistrano-rails',       '~> 1.2', require: false
  gem 'capistrano-rvm',         '~> 0.1', require: false

  # Use 'thin' to avoid "Could not determine content-length of response body." warnings.
  # @see (http://stackoverflow.com/questions/7082364/what-does-warn-could-not-determine-content-length-of-response-body-mean-and-h)
  gem 'thin'

  # https://github.com/voormedia/rails-erd, https://news.ycombinator.com/item?id=18324132
  gem 'rails-erd'

  gem 'better_errors', '~> 2.3' # Improved version of the Rails error page
  gem 'binding_of_caller'       # ^ Enables better_errors' advanced features
  gem 'pry-doc'                 # Extends pry with MRI documentation
  gem 'pry-rails'               # Use pry for `rails console`

  gem 'derailed_benchmarks'     # Tools for benchmarking ruby apps
  gem 'stackprof'               # Ruby call-stack profiler

  gem 'bullet'                  # Tool to eliminate N+1 queries and unused loading
  gem 'rails_best_practices'    # Code metric tool for quality checks
  gem 'rubocop', '~> 1.0', require: false # Static code analyzer. Enforces the Ruby Style Guide
  gem 'rubocop-minitest', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'

  gem 'simplecov', require: false # Track code coverage of test suite

  # TODO: required by rails 5.1.4. Remove (to match production) after these release:
  # * https://github.com/rails/rails/pull/30638
  # * https://github.com/rails/rails/commit/50f697664edf0d2deff22f3f1a1c8e01d54a74ca
  gem 'puma'
end

gem 'sdoc', '~> 2.0', group: :doc # `rails doc:rails` generates the API under doc/api.
gem 'rdoc', '< 6.4', require: false # TODO: unpin once psych 4 issue resolved
