# REVIEW THIS GENERATED GEMFILE, THEN DELETE THIS COMMENT.
# When applying to an existing project, you must restore any project gems we blew away!

source 'https://rubygems.org'

gem 'rails', '~> 5.0.1'
# TODO: replace use of content_tag_for, then remove this gem
# (https://github.com/rails/rails/issues/18337) discussion of why to remove from rails
# (https://github.com/rails/rails/pull/18411) does the work of moving from rails to gem
gem 'record_tag_helper', '~> 1.0' #content_tag_for deprecated in Rails 5

gem 'dotenv-rails'              # Loads environment variables from .env into ENV, automagically.
gem 'pg', '~> 0.19'             # Use postgresql as the database for Active Record

gem 'authlogic', '~> 3.5.0'     # Authentication
gem 'scrypt'                    # required by authlogic when using scrypt
gem 'cancancan', '~> 1.15'      # Authorization
gem 'will_paginate', '~> 3.1.0'
gem 'exception_notification', '~> 4.2.0'
gem 'slack-notifier'            # Send exception notifications to Slack
gem 'active_model_serializers', '~> 0.10.0' # building JSON responses
gem 'sitemap_generator'         # Generation setup in config/sitemap.rb
gem 'whenever', require: false
gem 'colorize'                  # Colored console output
gem 'friendly_id', '~> 5.2.0'   # Pretty URLs
gem 'paper_trail', '~> 5.2.0'   # Track model revisions
gem 'virtus'                    # Define typed attributes (e.g. for Value Objects, Form Objects)

# Styling

gem 'sass-rails', '~> 5.0' # Use SCSS for stylesheets
gem 'font-awesome-sass', '~> 4.7.0'
gem 'bootstrap-sass', '~> 3.3.0'
gem 'bootstrap-datepicker-rails'

# Javascript

gem 'therubyracer', platforms: :ruby # See https://github.com/rails/execjs#readme for more supported runtimes
gem 'uglifier', '>= 1.3.0'      # Use Uglifier as compressor for JavaScript assets
gem 'coffee-rails', '~> 4.2.0'  # Use CoffeeScript for .coffee assets and views
gem 'jquery-rails'              # Use jquery as the JavaScript library
gem 'underscore-rails'          # utility-belt library for JavaScript

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri

  gem 'factory_girl_rails'
  gem 'rspec-rails', '~> 3.0'
  gem 'capybara'
  gem 'faker'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
  gem 'listen', '~> 3.1'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  gem 'capistrano',         '~> 3.7', require: false
  gem 'capistrano-rails',   '~> 1.2', require: false
  gem 'capistrano-rvm',     '~> 0.1', require: false
  gem 'capistrano-passenger'
  gem 'capistrano-maintenance', '~> 1.0', require:false

  # Use 'thin' to avoid "Could not determine content-length of response body." warnings.
  # @see (http://stackoverflow.com/questions/7082364/what-does-warn-could-not-determine-content-length-of-response-body-mean-and-h)
  gem 'thin'

  gem 'better_errors' # TODO: 2.1.1 uses deprecated :original_exception. Update when fix released.
  gem 'binding_of_caller'
  gem 'rails_best_practices'
  gem 'pry-rails'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'sdoc', '~> 0.4.0', group: :doc # bundle exec rake doc:rails generates the API under doc/api.
